### PR TITLE
Don't expect encoding-indexes to return object with indexes & don't require them if they are already present

### LINKED ISSUE #60: encoding-indexes aren't properly loaded
Getting `Uncaught TypeError: Cannot read property 'ibm866' of undefined` error in client-console. It's likely an issues occurs due to [expectation](https://github.com/inexorabletash/text-encoding/blob/master/lib/encoding.js#L11) that `encoding-indexes.js` returns an object with encoding-indexes whereas it assigns them to global object.

### PR DESCRIPTION
**Pull request by epaminond**
Intended to fix #60.

### CODE REVIEW

**Comment by inexorabletash** [comment]
Sure; since I don't use node/require/etc I'll rely on y'all to let me know if this works (or breaks things)

**Comment by inexorabletash** [comment]
Thanks for the report/fix, though! And fingers crossed that it works.

**Comment by epaminond** [comment]
Works for me. :)

**Comment by cgav** [comment]
Could you please publish those changes to npm?

**Comment by inexorabletash** [comment]
@cgav - done! Thanks for the reminder.

https://github.com/inexorabletash/text-encoding/releases/tag/v0.6.2

**Pull request merged**
